### ISSUE TITLE
xcode 8.3.1 upgrade之后报错

### ISSUE THREAD

**Issue by sadpig1993** [zzz945/RNAlibcSdkDemo#1]
![image](https://cloud.githubusercontent.com/assets/3955216/24948687/b402b55c-1f9d-11e7-97ce-094d8881bcb0.png)

**Comment by sadpig1993** [comment]
```
// 引入sdk
import AlibcSdk from 'react-native-alibc-sdk';
```
引入的sdk是AlibcSdk undefined

**Comment by zzz945** [comment]
升级前没问题是吗， 重新clone、install， 运行react-native run-ios试试， 八成是开发环境引起的问题吧
