### ISSUE TITLE
真机调试bitcode要设置成No

### ISSUE THREAD

**Issue by sadpig1993** [zzz945/RNAlibcSdkDemo#2]
否则无法真机调试
![image](https://cloud.githubusercontent.com/assets/3955216/24997759/5499954a-206a-11e7-8770-7efb4b84ce8c.png)

另外，真机在唤起手淘登录之后授权失败
![image](https://cloud.githubusercontent.com/assets/3955216/24997810/91f349ae-206a-11e7-832e-4a03217a46f1.png)

**Comment by sadpig1993** [comment]
真机调试唤起手淘登录授权之后跳回demo，检查islogin，是false

**Comment by zzz945** [comment]
在android真机调试过没问题，没有在ios上真机调试过，如有进展请告知，谢谢

**Comment by sadpig1993** [comment]
错误码是104，查官方文档都查不到。tb_back_without_auth

**Comment by zzz945** [comment]
问题解决了， 需要在AppDelegate.m加代码让sdk处理跳转结果，试试

**Comment by sadpig1993** [comment]
嗯~解决了~
